/**
 * Pure buzz transition for a tournament room.
 *
 * This is the one place that decides the thing the whole product is judged on: who pressed
 * first. It is a synchronous function of the current state and the server's receive time, so
 * that two buzzes arriving in the same tick are applied one after the other with nothing in
 * between. The socket handler does its I/O first and then hands this transition to
 * `RoomRegistry.update()`; the domain lint rules reject `async`, `await` and `Date.now()`
 * here so that the sequence cannot be broken later by accident.
 *
 * Ordering is positional, not timestamped: the rank of a buzz is its index in `buzzOrder`.
 * `receivedAt` is recorded for display only and is never compared to decide who was first,
 * because two entries can legitimately share a millisecond.
 *
 * Rejections all use `INVALID_STATE`. A participant only needs to know that the buzzer does
 * not work right now, and a finer set of codes would let a client infer room state it is not
 * being shown. Refusal also returns no state, so a mashed button neither reorders anything
 * nor triggers a broadcast to everyone in the room.
 */

import type { BuzzEntry, InternalRoomState, ParticipantState } from '@quiz-world/shared';
import { accept, reject, type TransitionResult } from './transition';

export type BuzzInput = {
  /** Resolved from the socket session, never taken from the client payload. */
  participantId: string;
  /** Used only when this buzz opens a new round. Generated by the caller. */
  newBuzzSessionId: string;
  /** Server receive time in epoch milliseconds. */
  now: number;
};

/**
 * Records a buzz, opening a round when the room is idle.
 *
 * `idle` is the only status that starts a round: the presser becomes the responder and the
 * room moves to `answering`. During `answering` the buzzer stays live for everyone who has
 * not pressed yet, but their press only queues them up — the answer right moves solely by
 * the host's judgement, never by another participant pressing.
 *
 * The host seat is refused. The host holds a participant entry so that reconnects and the
 * display name check have something to work with, but letting the person who decides
 * correctness also hold the answer right is not a state worth being able to reach.
 */
export function applyBuzz(current: InternalRoomState, input: BuzzInput): TransitionResult {
  const seat = findSeat(current.participants, input.participantId);
  if (seat === undefined || seat.id === current.hostId) {
    return reject('INVALID_STATE');
  }

  const entry: BuzzEntry = { participantId: seat.id, receivedAt: input.now };

  if (current.status === 'idle') {
    return accept({
      ...current,
      status: 'answering',
      currentBuzzSession: { id: input.newBuzzSessionId, startedAt: input.now },
      buzzOrder: [entry],
      currentResponderId: seat.id,
      updatedAt: input.now,
    });
  }

  if (current.status !== 'answering') {
    return reject('INVALID_STATE');
  }

  if (hasBuzzed(current.buzzOrder, seat.id)) {
    return reject('INVALID_STATE');
  }

  return accept({
    ...current,
    buzzOrder: [...current.buzzOrder, entry],
    updatedAt: input.now,
  });
}

function findSeat(
  participants: readonly ParticipantState[],
  participantId: string,
): ParticipantState | undefined {
  return participants.find((participant) => participant.id === participantId);
}

function hasBuzzed(buzzOrder: readonly BuzzEntry[], participantId: string): boolean {
  return buzzOrder.some((entry) => entry.participantId === participantId);
}
