/**
 * Tournament settings, the only thing the platform persists beyond a crash-recovery
 * snapshot.
 *
 * A tournament is created once over HTTP and then lives in DynamoDB. Everything that
 * happens during play (buzzes, answers, scores) stays in the socket server's memory and is
 * never written here.
 *
 * Two shapes are distinguished on purpose. `Tournament` is what clients may see;
 * `TournamentRecord` is what the table holds and additionally carries the hashed host
 * token. Keeping them apart means leaking the hash requires deliberately widening a type.
 */

/** Every tournament status. Listed so that stored values can be validated on read. */
export const TOURNAMENT_STATUSES = ['active', 'closed'] as const;

/**
 * Lifecycle of a tournament.
 *
 * - `active`: set at creation. Participants may join immediately; there is no separate
 *   "start" operation.
 * - `closed`: the host closed the room. Nobody new can join, but the host can still
 *   reconnect to look at the final result.
 */
export type TournamentStatus = (typeof TOURNAMENT_STATUSES)[number];

/**
 * Tournament settings as exposed to clients.
 *
 * Safe to send to anyone who already knows the invite code: it carries no credentials.
 */
export type Tournament = {
  /** Server-issued UUID, used as the DynamoDB partition key and the socket room key. */
  id: string;
  /** Trimmed name shown to participants before they join. */
  name: string;
  /** Upper bound checked when someone joins for the first time. Rejoins bypass it. */
  maxParticipants: number;
  /** Eight characters, generated by the server and stored normalised to upper case. */
  inviteCode: string;
  status: TournamentStatus;
  createdAt: number;
  updatedAt: number;
};

/**
 * Tournament settings as stored in DynamoDB.
 *
 * Must never be returned from an HTTP handler or a socket event; convert to `Tournament`
 * first.
 */
export type TournamentRecord = Tournament & {
  /**
   * SHA-256 hash of the host token. The plaintext token is shown once, in the creation
   * response, and is never stored or recoverable.
   */
  hostTokenHash: string;
  /**
   * Reserved for the Cognito integration in phase 2, where it will hold the host's `sub`.
   * Always unset in the MVP, so that tournaments created now keep working on token auth
   * after accounts are introduced.
   */
  hostAccountId?: string;
};
